### ISSUE TITLE
Toast that URL has been copied

### ISSUE THREAD

**Issue by mizzunet** [TacoTheDank/Scoop#5]
Show toast message for letting to know and the notification may be cleared itself after that because after getting URL

**Comment by Vendicated** [comment]
the way I understood it:

once you press the dogbin upload button, it should show a notification "Url copied to your clipboard" and close the notification

**Comment by TacoTheDank** [comment]
Hey Ven,

Yeah, except that Scoop already does that except in a more manual fashion. You press "Upload to dogbin" (with internet), the notification does the upload, then you click "Copy url" (which displays a toast message of "Stack trace link copied to clipboard"), and finally swipe the notification away to close it.

@mizzunet It would be very helpful if you could clarify what you meant. Otherwise I'll have no choice but to close this issue, and I don't want to do that if nothing was actually resolved on either end.

**Comment by TacoTheDank** [comment]
No response from OP.
