### ISSUE TITLE
Add xposed back

### ISSUE THREAD

**Issue by ravilov** [TacoTheDank/Scoop#8]
Please consider adding Xposed part back. It was very much used and works perfectly. I've been using it like that for a very long time now. It eliminates the need for a background service and a permanent notification. Hooking directly into an app's crash handler is a much more elegant approach than constantly monitoring logcat.

**Comment by binarynoise** [comment]
Came here to say the same. 

Using xposed also catches some crashes that aren't logged to logcat

**Comment by TacoTheDank** [comment]
Well, ok, sure. Only the GitHub-flavored releases will support it though.

JCenter is deprecated, but it's where the Xposed API libraries are maintained. JCenter will eventually shut down, so I have to add them locally so they don't suddenly disappear on me. However, F-Droid does not support building apps with precompiled binaries for security reasons. Thus, I can only support Xposed through GitHub releases.

Just remember to use the GitHub releases if you want to use Scoop with Xposed. Also, remember to check for updates every now and again, as people using my GitHub releases won't be able to update the app through F-Droid due to different key signatures. There's a source code link in the app's about section so it should be pretty easy to check if there's a new release.

Thanks!

**Comment by binarynoise** [comment]
Thank you!

**Comment by binarynoise** [comment]
An idea to circumvent jcenter:
Can't we add the xposed-api-repo as git submodule/subrepo or something similar?

And I just found out: 
rovo89 tries to host a maven repo on the github pages:
[https://github.com/rovo89/XposedBridge/commit/79f70cf567fdb42f83313f6cad97a6ffc878f3ac](see this commit)

**Comment by TacoTheDank** [comment]
@binarynoise Ah I didn't notice he had set up a thing like that.

Just our luck though, F-Droid also maintains their own list of [repositories they allow](https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/scanner.py#L152), so that wouldn't be possible either :(

I did think about adding it as a submodule. However, that's one more thing that F-Droid would have to go through and verify every time, and it makes the Scoop repository more cluttered as well. I figure it wouldn't really be worth it.

**Comment by binarynoise** [comment]
jitpack.io is allowed, so it should be possible to use that to get the xposed api. Alternatively we  could create an issue to encourage the xposed maintainer to move to one of the accepted platforms

**Comment by TacoTheDank** [comment]
Dang, I actually completely forgot about Jitpack there.

...the builds still fail https://jitpack.io/#rovo89/XposedBridge :(

Only option now is to open an issue and see if he responds.

**Comment by TacoTheDank** [comment]
Decided to just add back Xposed using Jcenter for the time being. If this isn't resolved by the time Jcenter officially shuts down, then I'll have to remove Xposed support for F-Droid.
