### ISSUE TITLE
StackTrace text is unselectable

### ISSUE THREAD

**Issue by LoganDark** [TacoTheDank/Scoop#81]
it's annoying to have to copy the entire stack trace to the clipboard just to paste it into another app in order to obtain the part that I actually want. it would be nice if scoop used a readonly textbox for the stack trace, rather than a normal label, so that text can be selected and copied directly from there.

**Comment by TacoTheDank** [comment]
Sorry for the late response, but this is already possible if you press the "toggle selection mode" icon next to the search icon. You can then select the portion that you want.

**Comment by LoganDark** [comment]
Bit weird that you have to activate a special mode to do this. But thanks!

**Comment by TacoTheDank** [comment]
Yeah, I'm not happy with the app design. That's usually what happens when working with several-years-old code originally written by someone else.

I've been wanting to completely rewrite and redesign it from the ground up for a long while (because the code is terribly designed and hard-to-understand in several places), but trying to keep up with yearly Android releases and all their API changes is so tiring. Life stuff, school, and other priorities also get in the way, and lower-importance hobby stuff like this takes the backburner. Also, there was a change in Android 13 that severely restricts this app's functionality (which further dampens my motivation). A majority of open issues are just a result of the app's flawed design that would take a bunch of rewriting to fix, and I don't want to do that. I'd rather just throw it all out and start anew. Ironically, that would require me to dedicate a bunch of time to studying Compose, but I'd be willing to do that.

Sorry for the dump, but I felt it was pretty relevant lol.

**Comment by binarynoise** [comment]
It might be worth looking at alternatives like [LogFox](https://github.com/F0x1d/LogFox) and port missing functionality there. They found a way to cope with the restrictions.
